import type { NavItemConfig } from '@/types/nav';
import { paths } from '@/paths';

export const navItems = [
  { key: 'overview', title_eng: 'Main', title_ka: 'მთავარი', href: paths.dashboard.overview, icon: 'chart-pie' },
  // {
  //   key: 'addPost',
  //   title_eng: 'Add post',
  //   title_ka: 'განცხადების დამატება',
  //   href: paths.dashboard.addPost,
  //   icon: 'users',
  // },
  {
    key: 'addVacancy',
    title_eng: 'Add vacancy',
    title_ka: 'ვაკანსიის დამატება',
    href: paths.dashboard.addVacancy,
    icon: 'users',
  },
  // {
  //   key: 'agenda',
  //   title_eng: 'Agenda data',
  //   title_ka: 'აჯენდა',
  //   href: paths.dashboard.agenda,
  //   icon: 'users',
  // },
  {
    key: 'publishedVacancies',
    title_eng: 'Published vacancies',
    title_ka: 'გამოქვეყნებული ვაკანსიები',
    href: paths.dashboard.publishedVacancies,
    icon: 'users',
  },
  {
    key: 'contactForms',
    title_eng: 'Contact forms',
    title_ka: 'საკონტაქტო ფორმები',
    href: paths.dashboard.contactForms,
    icon: 'users',
  },
  // {
  //   key: 'galleryUpload',
  //   title_eng: 'Photo gallery',
  //   title_ka: 'გალერია',
  //   href: paths.dashboard.galleryUpload,
  //   icon: 'users',
  // },
  // {
  //   key: 'addSpeaker',
  //   title_eng: 'Add speaker',
  //   title_ka: 'სპიკერის დამატება',
  //   href: paths.dashboard.addSpeaker,
  //   icon: 'users',
  // },
  // {
  //   key: 'speakers',
  //   title_eng: 'Speakers',
  //   title_ka: 'სპიკერები',
  //   href: paths.dashboard.speakers,
  //   icon: 'users',
  // },
  // {
  //   key: 'addAgenda',
  //   title_eng: 'Add Agenda',
  //   title_ka: 'აჯენდის დამატება',
  //   href: paths.dashboard.addAgenda,
  //   icon: 'users',
  // },
  // {
  //   key: 'addSponsor',
  //   title_eng: 'Add Sponsor',
  //   title_ka: 'სპონსორის დამატება',
  //   href: paths.dashboard.addSponsor,
  //   icon: 'users',
  // },
  // {
  //   key: 'sponsors',
  //   title_eng: 'Sponsors',
  //   title_ka: 'სპონსორები',
  //   href: paths.dashboard.sponsors,
  //   icon: 'users',
  // },
  // {
  //   key: 'settings',
  //   title_eng: 'Settings',
  //   title_ka: 'პარამეტრები',
  //   href: paths.dashboard.settings,
  //   icon: 'gear-six',
  // },
  // {
  //   key: 'account',
  //   title_eng: 'Account',
  //   title_ka: 'პროფილი',
  //   href: paths.dashboard.account,
  //   icon: 'user',
  // },
] satisfies NavItemConfig[];
